(?#)
(?# USE PYTHON REGEX SYNTAX, TweakRecon[in lib folder] or KODOS to CHECK )
(?# THE <MATCH_GROUP_NAME> and filename must be the same)
(?#)
(?# TARGET> A|O|P|R DDHHMMZ MMM YY )
(?#)
(?#FLAGS: IGNORECASE,DOTALL)
(?#)
\b[AROP]\s(?P<date002>[0-3]\d[0-2]\d[0-5]\dZ\s*(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEPT?|OCT|NOV|DEC)\s*\d{2})
